version: "3.3"

services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - auth_api

  auth_api:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    expose:
      - 8000
