version: "3.3"

services:
  nginx:
    build: ./nginx
    ports:
      - "8001:80"
    depends_on:
      - account_api

  account_api:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
    expose:
      - 8001
